### ISSUE TITLE
Need a message after recording a student's grade

### ISSUE THREAD

**Issue by slankas** [shaowns/SoftSecAttendanceTracker#19]
Need something like 'unity (or name) marked as x' 
ie, set a message in the request object while recording the score.  if that message exists, display it.

**Comment by slankas** [comment]
Once a message has been displayed, it no longer needs to be shown.

we just need some feedback as to what occured.  App didn't provide that before

**Comment by slankas** [comment]
now there's no message.... 
this is isn't hard and this should be standard feedback to a user.  When you perform an action, you need to see some feedback that it's actually occurred.  Once the user has received that feedback, there no's reason to continue to show it.

**Comment by sdshao** [comment]
![screenshot](https://user-images.githubusercontent.com/23385703/30546605-1417c5ba-9c5b-11e7-88ea-3aa1f7975a8d.jpeg)
Hi, @slankas ,
It's weird. There should be a message above the top of the name list, like the screenshot. Once you grade another one, the message will be replaced. Or if you re-login, there will be no message again. However, I will try to find another way to display the message.

**Comment by slankas** [comment]
@sdshao this may have a been my mistake.  I just tried it again and was successful with the message.
